create table "public"."analytics_report_recipients" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "name" text,
    "email" text,
    "store_report" boolean,
    "energiser_report" boolean,
    "general_report" boolean
);


alter table "public"."analytics_report_recipients" enable row level security;

CREATE UNIQUE INDEX analytics_report_recipients_pkey ON public.analytics_report_recipients USING btree (id);

alter table "public"."analytics_report_recipients" add constraint "analytics_report_recipients_pkey" PRIMARY KEY using index "analytics_report_recipients_pkey";

create policy "Enable read access for all users"
on "public"."analytics_report_recipients"
as permissive
for select
to public
using (true);



