create table "public"."installers" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "address" text,
    "postcode" text,
    "latitude" double precision,
    "longitude" double precision,
    "name" text
);
CREATE UNIQUE INDEX installers_pkey ON public.installers USING btree (id);
alter table "public"."installers" add constraint "installers_pkey" PRIMARY KEY using index "installers_pkey";
