create table "public"."jobs" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "address" text,
    "postcode" text,
    "latitude" double precision,
    "longitude" double precision,
    "name" text
);
alter table "public"."jobs" enable row level security;
alter table "public"."installers" enable row level security;
CREATE UNIQUE INDEX jobs_pkey ON public.jobs USING btree (id);
alter table "public"."jobs" add constraint "jobs_pkey" PRIMARY KEY using index "jobs_pkey";
