create table "public"."prism-leads" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "data" json
);


CREATE UNIQUE INDEX "prism-leads_id_key" ON public."prism-leads" USING btree (id);

CREATE UNIQUE INDEX "prism-leads_pkey" ON public."prism-leads" USING btree (id);

alter table "public"."prism-leads" add constraint "prism-leads_pkey" PRIMARY KEY using index "prism-leads_pkey";

alter table "public"."prism-leads" add constraint "prism-leads_id_key" UNIQUE using index "prism-leads_id_key";


